#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/corne/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# Try to fix dolphin not showin icons
export QT_QPA_PLATFORMTHEME="qt5ct"
export GTK_THEME="Breeze-Dark"
export XDG_CURRENT_DESKTOP=fluxbox

# Applications at startup
klipper &
slack &
ksnip &
kalarm &
gkrellm -w &
/usr/bin/xscreensaver -nosplash &
/home/corne/.screenlayout/eric-pc.sh &
#/usr/lib/notification-daemon/notification-daemon &
/usr/lib/mate-notification-daemon/mate-notification-daemon &


# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/corne/.fluxbox/log"
